default: &default
  dryrun_mode: true
  relays: ["wss://nostr.bitcoiner.social", "wss://nostr-pub.wellorder.net", "wss://relay.nostr.ro", "wss://relay.snort.social", "wss://relay.damus.io", "wss://nostr.rocks"]
  # sms2nostr_host: https://sms2nostr.yourdomain.com
  # sms2nostr_nsec: nsec1xxxxxxxxxxxxxxxxxxxxxxxxxxx
  # show_number_on_sos: false
  # dm_recipient: npub1zzzzzzzzzzzzzzzzzzzzzzz
  # sos_mode: false
  # antispam_mode: false

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default